image animated_bg:
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (1).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (2).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (3).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (4).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (5).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (6).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (7).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (8).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (9).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (10).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (11).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (12).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (13).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (14).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (15).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (16).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (17).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (18).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (19).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (20).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (21).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (22).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (23).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (23).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (24).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (25).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (26).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (26).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (27).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (28).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (29).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (30).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (31).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (32).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (33).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (34).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (35).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (36).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (37).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (38).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (39).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (40).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (41).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (42).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (43).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (44).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (45).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (46).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (47).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (48).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (49).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (50).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (51).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (52).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (53).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (54).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (55).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (56).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (57).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (58).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (59).png"
    pause 0.08
    "gui/imaginary_friends/bg_main_menu_night/bg_main_menu_night (60).png"
    pause 0.08
    repeat